name: Deploy Docs
on:
  push:
    branches:
      - vue3
    paths:
      - 'docs/**/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.QLIN_GITEE_TOKEN }}
        BRANCH: master
        FOLDER: docs/.vuepress/dist
        BUILD_SCRIPT: npm install && npm run docs:build
